site_name: Lucretia Field - MDEF
site_description: Master in Design for Emergent Futures
site_author: Lucretia Field
site_url: https://lkfield.github.io/mdef/
repo_url: https://github.com/LKField/mdef

copyright: Copyleft 2024 "Lucretia Field" - GNU Free Documentation License
repo_name: 'LKField : mdef'

# navigation 
nav:
  - Home: index.md
  - About: about/me.md
    # - Reading: about/reading.md
  - Design Studio:
    - Design Space: designSpace.md
    - Studio Overview: designOverview.md

  - Term 1:
      - Design Studio 01:
        - Intro Week: term1/designStudio/designWK01.md
        - Session Two: term1/designStudio/designWK02.md
        - Session Three: term1/designStudio/designWK03.md
        - Session Four: term1/designStudio/designWK04.md
        - End of Term: term1/designStudio/termEnd.md
      #  - Design Space: designSpace.md
      - Landing: term1/landing.md
      - Documenting Design: term1/documenting.md
      - Fundamentals of Digital Fabrication: term1/digfab.md
      - Machine Paradox: term1/machineParadox.md
      - Living With Your Own Ideas: term1/ownIdeas.md
      - Extended Intelligences: term1/extendedIntelligence.md
      - Design with Others: term1/withOthers.md
      - Biology Zero: term1/biologyZero.md
      - Agriculture Zero: term1/agricultureZero.md

  - Term 2: 
    - Design Studio 02:
      - Session One: term2/designStudio/design02WK01.md
      - Session Two: term2/designStudio/design02WK02.md
    - Communicating Ideas: term2/communicating.md
    - Living Materials: term2/materials.md
  #   - Collective Intelligences: term2/collective.md
    
    


# theme edits 
theme:
  name: material
    # custom_dir: overrides
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    scheme: slate         # slate = #1d2129
    primary: deep purple  # deep purple = #7e56c1
    accent: orange        # orange = #ff9108
  font:
    # See available fonts at https://fonts.google.com/
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate

# added markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  # for icons/emjois from https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # for code from https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  # pygments from https://pygments.org/styles/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

extra_css:
  - style.css

extra_javascript:
  - extra.js

# plugins:
#   - glightbox